//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leno_Inventory_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankdetailsTable
    {
        public long empno { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public long phoneno { get; set; }
        public long bankacno { get; set; }
        public string bankname { get; set; }
        public string branchname { get; set; }
        public string ifsccode { get; set; }
        public string micrcode { get; set; }
        public string status { get; set; }
    }
}
