//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leno_Inventory_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class billTable
    {
        public long billno { get; set; }
        public string invoiceno { get; set; }
        public System.DateTime date { get; set; }
        public long deliveryno { get; set; }
        public System.DateTime notedate { get; set; }
        public long customerid { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public string gstno { get; set; }
        public string destination { get; set; }
        public string vechicleno { get; set; }
        public string goodscondition { get; set; }
        public string goodsdescription { get; set; }
        public long hsn { get; set; }
        public long quantity { get; set; }
        public long rateper { get; set; }
        public long amount { get; set; }
        public long sgst { get; set; }
        public long cgst { get; set; }
        public long totalamount { get; set; }
    }
}
