//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leno_Inventory_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerTable
    {
        public long customerid { get; set; }
        public long typeid { get; set; }
        public string companyname { get; set; }
        public string emailid { get; set; }
        public string gstno { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string statecode { get; set; }
        public long zipcode { get; set; }
        public string igst { get; set; }
        public string status { get; set; }
    }
}
