//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leno_Inventory_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class profileTable
    {
        public long empno { get; set; }
        public string name { get; set; }
        public long age { get; set; }
        public string category { get; set; }
        public long phoneno { get; set; }
        public string vehicleno { get; set; }
        public string address { get; set; }
        public long aadharno { get; set; }
        public string panno { get; set; }
        public string emailid { get; set; }
        public long bankacno { get; set; }
        public int balance { get; set; }
    }
}
