//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leno_Inventory_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseTable
    {
        public string invoiceno { get; set; }
        public long vendorid { get; set; }
        public string gstid { get; set; }
        public System.DateTime purchasedate { get; set; }
        public string category { get; set; }
        public long hsn { get; set; }
        public long quantity { get; set; }
        public long perprice { get; set; }
        public long totalprice { get; set; }
        public long disc { get; set; }
        public long totalamount { get; set; }
        public long currentbalance { get; set; }
        public long balance { get; set; }
        public long bankacno { get; set; }
        public long checkno { get; set; }
        public System.DateTime date { get; set; }
    }
}
