//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leno_Inventory_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class rawmaterialsTable
    {
        public long idno { get; set; }
        public long code { get; set; }
        public string category { get; set; }
        public string color { get; set; }
        public string size { get; set; }
        public string inch { get; set; }
        public string type { get; set; }
        public string status { get; set; }
    }
}
