//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leno_Inventory_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockTable
    {
        public string modelno { get; set; }
        public long capacity { get; set; }
        public long weight { get; set; }
        public string dimension { get; set; }
        public long tax { get; set; }
        public long price { get; set; }
        public long quantity { get; set; }
    }
}
