//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leno_Inventory_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockoutTable
    {
        public long idno { get; set; }
        public string modelno { get; set; }
        public long billno { get; set; }
        public string invoiceno { get; set; }
        public System.DateTime date { get; set; }
        public string company { get; set; }
        public long sold { get; set; }
    }
}
