//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leno_Inventory_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class travellerTable
    {
        public long travelid { get; set; }
        public string name { get; set; }
        public long empno { get; set; }
        public string category { get; set; }
        public string vehicleno { get; set; }
        public long phoneno { get; set; }
        public System.DateTime date { get; set; }
        public string company { get; set; }
        public string start { get; set; }
        public string stop { get; set; }
        public long kilometer { get; set; }
        public long cost { get; set; }
    }
}
