//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leno_Inventory_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class workerTable
    {
        public long paidno { get; set; }
        public long empno { get; set; }
        public string category { get; set; }
        public string name { get; set; }
        public long bankacno { get; set; }
        public System.DateTime paiddate { get; set; }
        public string shift { get; set; }
        public long hours { get; set; }
        public string mode { get; set; }
        public long paid { get; set; }
    }
}
